import type { Metadata } from "next";

import "../globals.scss";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import { languages } from "@/lib/use-translation/languages-data";
import { Lang } from "@/lib/use-translation/types";
import { RootChildrenType } from "./types";
import { languageDirection } from "@/lib/use-translation/direction";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AppProviders } from "../components/queryProviders";
import { Header } from "../components/Header";
import { Ping } from "../components/ping";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }: RootChildrenType) {
  if (!languages.includes(params.locale)) {
    params.locale ?? (process.env.DEFAULT_LANG as Lang) ?? "fr";
  }

  return (
    <html
      lang={params.locale}
      dir={languageDirection(params.locale)}
      suppressHydrationWarning
    >
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <AppProviders>
        <Ping />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header locale={params.locale} />
            {children}
          </ThemeProvider>
        </AppProviders>
      </body>
    </html>
  );
}
